obj-y = head.o cpu.o cpuid.o

dir-$(CONFIG_S3C24X)     = s3c24x
dir-$(CONFIG_S3C6410)     = s3c64x
dir-$(CONFIG_AT91)        = at91
dir-$(CONFIG_OMAP3)       = omap3
dir-$(CONFIG_OMAP4)       = omap4

PHONY += head.S
