# UART Core Files
obj-y = uart.o

obj-$(CONFIG_UART_S3C24X) += s3c24x_uart.o
obj-$(CONFIG_UART_S3C64X) += s3c64x_uart.o
obj-$(CONFIG_UART_AT91)   += at91_uart.o
obj-$(CONFIG_UART_OMAP3)  += omap3_uart.o
obj-$(CONFIG_UART_OMAP4)  += omap4_uart.o
obj-$(CONFIG_E310_UART)   += e310_uart.o
obj-$(CONFIG_K210_UART)   += k210_uart.o
obj-$(CONFIG_WUJIAN100_UART)   += wujian100_uart.o
